In [1]:
#Imports 

import pandas as pd
import numpy as np

import mlflow
import mlflow.sklearn

from sklearn.model_selection import train_test_split

from sklearn.linear_model import (
    LinearRegression,
    Ridge
)

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [2]:
#Configuração do MLflow

mlflow.set_tracking_uri("sqlite:///mlflow.db")

mlflow.set_experiment("Ridge_Regression")

mlflow.sklearn.autolog()

In [3]:
#Carregar o nosso dataset

df = pd.read_csv("../DATASET/dataset_expandido.csv")

In [4]:
#Preparar dataset (dados)

df["YearsCodePro_Num"] = df["YearsCodePro"]

df["YearsCodePro_Num"] = (
    df["YearsCodePro_Num"]
    .replace({
        "Less than 1 year": 0,
        "More than 50 years": 51,
        "Sem dado": 0
    })
)

df["YearsCodePro_Num"] = pd.to_numeric(
    df["YearsCodePro_Num"]
)

features = [

    "YearsCodePro_Num",

    "WorkExp",

    "Age_Code"

]

target = "ConvertedCompYearly"

X = df[features]

y = df[target]

print("Número de features:", len(features))

print(features)

Número de features: 3
['YearsCodePro_Num', 'WorkExp', 'Age_Code']


In [5]:
#Divisão dos dados em treino e teste

X_train, X_test, y_train, y_test = (train_test_split(X, y, test_size=0.2, random_state=42))

In [6]:
#Experiencia Do Ridge


def run_ridge_experiment(
    run_name,
    alpha
):

    with mlflow.start_run(
        run_name=run_name
    ):

        model = Ridge(
            alpha=alpha
        )

        model.fit(
            X_train,
            y_train
        )

        y_pred = model.predict(
            X_test
        )

        rmse = np.sqrt(
            mean_squared_error(
                y_test,
                y_pred
            )
        )

        r2 = r2_score(
            y_test,
            y_pred
        )

        mlflow.log_param(
            "alpha",
            alpha
        )

        mlflow.log_metric(
            "RMSE",
            rmse
        )

        mlflow.log_metric(
            "R2",
            r2
        )

        print(run_name)

        print(
            "Alpha:",
            alpha
        )

        print(
            "RMSE:",
            rmse
        )

        print(
            "R2:",
            r2
        )

        print(
            "Coefficients:"
        )

        print(
            model.coef_
        )

        print("-"*40)

        return model

In [35]:
#Experiencia 0 - Linear Regression Baseline

linear_model = LinearRegression()

linear_model.fit(
    X_train,
    y_train
)

print(
    linear_model.coef_
)

2026/05/21 23:25:34 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '1269209f70bc4e19954707e19de91cd3', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow
2026/05/21 23:25:35 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\luisr\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Inte

[799.34344869 804.43466193 162.22745526]


In [36]:
#Experiencia 1 - Ridge Regression com alpha = 0.01

ridge01 = run_ridge_experiment(
    run_name=
    "Experiment_1_Ridge_alpha_0.01",

    alpha=0.01
)

2026/05/21 23:25:42 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\luisr\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/05/21 23:25:42 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\luisr\AppData\Lo

Experiment_1_Ridge_alpha_0.01
Alpha: 0.01
RMSE: 137888.47965899445
R2: 0.007214354847959514
Coefficients:
[799.34344917 804.43466073 162.22744762]
----------------------------------------


In [37]:
#Experiencia 2 - Ridge Regression com alpha = 0.1

ridge1 = run_ridge_experiment(
    run_name=
    "Experiment_2_Ridge_alpha_0.1",

    alpha=0.1
)

2026/05/21 23:25:46 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\luisr\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/05/21 23:25:46 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\luisr\AppData\Lo

Experiment_2_Ridge_alpha_0.1
Alpha: 0.1
RMSE: 137888.47965932603
R2: 0.007214354843184667
Coefficients:
[799.34345346 804.43464985 162.22737887]
----------------------------------------


In [38]:
#Experiencia 3 - Ridge Regression com alpha = 1

ridge1 = run_ridge_experiment(
    run_name=
    "Experiment_3_Ridge_alpha_1",

    alpha=1
)

2026/05/21 23:25:51 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\luisr\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/05/21 23:25:51 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\luisr\AppData\Lo

Experiment_3_Ridge_alpha_1
Alpha: 1
RMSE: 137888.4796626418
R2: 0.007214354795438083
Coefficients:
[799.34349635 804.43454107 162.22669138]
----------------------------------------


In [39]:
#Experiencia 4 - Ridge Regression com alpha = 10

ridge10 = run_ridge_experiment(
    run_name=
    "Experiment_4_Ridge_alpha_10",

    alpha=10
)

2026/05/21 23:25:56 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\luisr\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/05/21 23:25:56 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\luisr\AppData\Lo

Experiment_4_Ridge_alpha_10
Alpha: 10
RMSE: 137888.47969579964
R2: 0.007214354317970462
Coefficients:
[799.34392526 804.4334533  162.21981716]
----------------------------------------


In [40]:
#Experiencia 5 - Ridge Regression com alpha = 100

ridge100 = run_ridge_experiment(
    run_name=
    "Experiment_5_Ridge_alpha_100",

    alpha=100
)

2026/05/21 23:26:04 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\luisr\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/05/21 23:26:04 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\luisr\AppData\Lo

Experiment_5_Ridge_alpha_100
Alpha: 100
RMSE: 137888.48002736963
R2: 0.0072143495434177085
Coefficients:
[799.34820851 804.42257452 162.15114186]
----------------------------------------


In [41]:
#Experiencia 6 - Ridge Regression com alpha = 1000

ridge1000 = run_ridge_experiment(
    run_name=
    "Experiment_6_Ridge_alpha_1000",

    alpha=1000
)

2026/05/21 23:26:08 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\luisr\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/05/21 23:26:08 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\luisr\AppData\Lo

Experiment_6_Ridge_alpha_1000
Alpha: 1000
RMSE: 137888.48334225317
R2: 0.007214301809642554
Coefficients:
[799.39046571 804.31367989 161.47101611]
----------------------------------------


### Introdução

A Ridge Regression foi aplicada utilizando as mesmas variáveis usadas anteriormete na Regressão Linear, mantendo a consistência entre os modelos avaliados.

Foram testados diferentes valores para o parâmetro alpha:

    -0.01
    -0.1
    -1
    -10
    -100
    -1000

O objetivo é analisar o impacto da regularização L2 no desempenho do modelo e no comportamento dos coeficientes. Os resultados mostraram alterações graduais no desempenho, à mdeida que o valor de alpha aumenta.

### ANÁLISE DE EXPERIÊNCIAS

# Experiência 1 - Regressão Linear Baseline

A regressão Linear apresentou o desempenho de referência para comparação com a regularização Ridge. O modelo apresentou capacidade preditiva reduzida, refletida pelos baixos valores de R² obtidos.

# Experiência 2 - Ridge alpha = 0.01

Com um valor muito reduzido de alpha, os resultados permaneceram praticamente idênticos aos obtidos pela Regressão Linear.Isto demonstrou um cómportamento que era esperado, porque a penalização aplicada é muito pequena.
Concluimos então que o modelo possui compprtamneto e resultados muito próximos do Baseline.

# Experiência 3 - Ridge alpha = 0.1

Com o valor de alpha = 0.1, observamos uma pequena, mas notável redução dos coeficientes. Apesar disso, o desempenho global sofreu alterações pouco significativas, permanecendo com resultados muito parecidos. 

Este tipo de comportamento, caracteriza a Ridge Regression, porque reduz a magnitude dos coeficientes sem eliminar variáveis.

# Experiência 4 - Ridge alpha = 1

À medida que o valor do alpha aumenta é cada vez mais notável a regularização. Os coeficientes continuam a diminuir e o modelo apresentou um compprtamento mais estável. 

Apesar disso, novamente os resultados globais continuam bastante próximos das experiências anteriores. Podemos então retirar como conclusões que o nosso dataset não apresenta grande MultiColineariedade.

# Experiência 5 - Ridge alpha = 10

Continuamos a aumentar o valor de alpha, mas a mudança de resultados é minima. Isso mostra que a redução dos coedicientes não produz ganhos relevantes na previsão salarial.

# Experiência 6 - Ridge alpha = 100

Depois de um grande aumento do valor de alpha em relação à experiencia anterior, verificamos que houve uma maior redução dos coeficientes. 

# Experiência 7 - Ridge alpha = 1000

Esta experiência foi a que teve o maior valor de alpha e consequentemente a que teve uma penalização mais forte. Mesmo assim o modelo não teve uma grande variação das métricas. Isso sugere-nos que as variéveis utilizadas tem pouca influência e uma baixa colineariedade.

# Análise de Coeficientes

A comparação entre o Rige e o Linear Regression mostra que a magnitude dos coeficientes diminuiu gradualmente e nenhuma variável foi removida. Este comportamento confirma a regularização L2.

A Ridge Regresion reduz a magnitude dos coeficientes, diminuindo a complexidade e a multicolineariedade, MAS preservando todas as variáveis.

### Conclusão

A Regressão Ridge apresentou comportamento semelhante à Regressão Linear, mas com coeficientes mais controlados. O aumento do alpha provocou o seguinte:

    . redução progresiva dos coeficientes;
    . manutenção das variáveis;
    . e pequenas alterações nas métricas.

Depois desta análise, cncluimos que a regularização L2 atuou principalmente sobre os coeficientes e não sobre a estrutura do modelo.

# Hyperparameter Optimization - Ridge Regression

In [7]:
import mlflow
import optuna

from sklearn.model_selection import (
    train_test_split,
    GridSearchCV,
    cross_val_score
)

from sklearn.linear_model import Ridge

In [8]:
target = "ConvertedCompYearly"

features = [

    "YearsCodePro_Num",

    "WorkExp",

    "Age_Code"

]

X = df[features]

y = df[target]

X_train, X_test, y_train, y_test = train_test_split(

    X,

    y,

    test_size=0.2,

    random_state=42

)

In [9]:
mlflow.sklearn.autolog(

    disable=True

)

In [10]:
param_grid = {

    "alpha":[

        0.001,

        0.01,

        0.1,

        1,

        10,

        100

    ]

}

grid = GridSearchCV(

    estimator=Ridge(),

    param_grid=param_grid,

    cv=10,

    scoring="r2",

    n_jobs=-1

)

grid.fit(

    X_train,

    y_train

)

print(

    "Best Parameters:",

    grid.best_params_

)

print(

    "Best Score:",

    grid.best_score_

)

Best Parameters: {'alpha': 100}
Best Score: 0.024757584819413637


In [11]:
with mlflow.start_run(

    run_name="GridSearch_Ridge"

):

    mlflow.log_param(

        "method",

        "GridSearch"

    )

    mlflow.log_params(

        grid.best_params_

    )

    mlflow.log_metric(

        "best_score",

        grid.best_score_

    )

2026/05/28 17:57:44 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet



In [12]:
def objective(

    trial

):

    alpha = trial.suggest_categorical(

        "alpha",

        [

            0.001,

            0.01,

            0.1,

            1,

            10,

            100

        ]

    )

    model = Ridge(

        alpha=alpha

    )

    scores = cross_val_score(

        model,

        X_train,

        y_train,

        cv=10,

        scoring="r2",

        n_jobs=-1

    )

    return scores.mean()

In [13]:
study = optuna.create_study(

    direction="maximize"

)

study.optimize(

    objective,

    n_trials=100

)

print(

    "Best Parameters:",

    study.best_params

)

print(

    "Best Score:",

    study.best_value

)

[I 2026-05-28 17:57:44,458] A new study created in memory with name: no-name-ed2e225a-fa52-4abb-ad7c-29f3507dfc14
[I 2026-05-28 17:57:44,941] Trial 0 finished with value: 0.02475758335073731 and parameters: {'alpha': 10}. Best is trial 0 with value: 0.02475758335073731.
[I 2026-05-28 17:57:45,439] Trial 1 finished with value: 0.02475758335073731 and parameters: {'alpha': 10}. Best is trial 0 with value: 0.02475758335073731.
[I 2026-05-28 17:57:45,922] Trial 2 finished with value: 0.024757583186298282 and parameters: {'alpha': 0.001}. Best is trial 0 with value: 0.02475758335073731.
[I 2026-05-28 17:57:46,385] Trial 3 finished with value: 0.02475758318792769 and parameters: {'alpha': 0.1}. Best is trial 0 with value: 0.02475758335073731.
[I 2026-05-28 17:57:46,890] Trial 4 finished with value: 0.024757583186298282 and parameters: {'alpha': 0.001}. Best is trial 0 with value: 0.02475758335073731.
[I 2026-05-28 17:57:47,301] Trial 5 finished with value: 0.024757583202738787 and parameters

Best Parameters: {'alpha': 100}
Best Score: 0.024757584819413637


In [14]:
with mlflow.start_run(

    run_name="Optuna_Ridge"

):

    mlflow.log_param(

        "method",

        "Optuna"

    )

    mlflow.log_params(

        study.best_params

    )

    mlflow.log_metric(

        "best_score",

        study.best_value

    )